"""Add entry types enum and site rate config

Revision ID: cc5ea3bd3568
Revises: 387078ecfbf5
Create Date: 2025-08-10 14:47:19.397933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc5ea3bd3568'
down_revision: Union[str, None] = '387078ecfbf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create site_rate_configs table with string-based entry_type for now
    op.create_table('site_rate_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(), nullable=False),  # Use string for compatibility
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'entry_type', name='_site_entry_type_rate_uc')
    )
    op.create_index(op.f('ix_site_rate_configs_id'), 'site_rate_configs', ['id'], unique=False)
    op.create_index(op.f('ix_site_rate_configs_site_id'), 'site_rate_configs', ['site_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_rate_configs_site_id'), table_name='site_rate_configs')
    op.drop_index(op.f('ix_site_rate_configs_id'), table_name='site_rate_configs')
    op.drop_table('site_rate_configs')
    # ### end Alembic commands ###
